apiVersion: v1
kind: Secret
metadata:
  name: mern-secret
  namespace: projet-vente-voiture
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL2hvc3QuZG9ja2VyLmludGVybmFsOjI3MDE3L3ZlbnRlX3ZvaXR1cmU=
  JWT_SECRET: c2VjcmV0X2V4YW1fbWVybg==
